[package]
name = "commonkit-service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
commonkit-contracts = { path = "../commonkit-contracts" }
rand.workspace = true
serde.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
tower.workspace = true
